version: '3'

services:
  postgres:
    image: postgres:9.6.3-alpine
    ports:
      - "5432:5432"

  loan:
    build: .
    ports:
      - "9001:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_USER=postgres
      - DATABASE_PASS=
